/*  =========================================================================
    zmailer_server - zmailer server

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef ZMAILER_SERVER_H_INCLUDED
#define ZMAILER_SERVER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/zmailer_server.xml" to make changes.
//  @interface
//  Create a new zmailer_server.
ZMAILER_EXPORT zmailer_server_t *
    zmailer_server_new ();

//  Destroy the zmailer_server.
ZMAILER_EXPORT void
    zmailer_server_destroy (zmailer_server_t **self_p);

//  Print properties of the zmailer_server object.
ZMAILER_EXPORT void
    zmailer_server_print (zmailer_server_t *self);

//  Self test of this class.
ZMAILER_EXPORT void
    zmailer_server_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
