/*  =========================================================================
    zmailer - ZMAILER wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef zmailer_library_H_INCLUDED
#define zmailer_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zmq.h>
#include <czmq.h>
#include <curl/curl.h>

//  ZMAILER version macros for compile-time API detection

#define ZMAILER_VERSION_MAJOR 1
#define ZMAILER_VERSION_MINOR 0
#define ZMAILER_VERSION_PATCH 0

#define ZMAILER_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZMAILER_VERSION \
    ZMAILER_MAKE_VERSION(ZMAILER_VERSION_MAJOR, ZMAILER_VERSION_MINOR, ZMAILER_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBZMAILER_STATIC
#       define ZMAILER_EXPORT
#   elif defined LIBZMAILER_EXPORTS
#       define ZMAILER_EXPORT __declspec(dllexport)
#   else
#       define ZMAILER_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZMAILER_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _zmailer_msg_t zmailer_msg_t;
#define ZMAILER_MSG_T_DEFINED
typedef struct _zmailer_server_t zmailer_server_t;
#define ZMAILER_SERVER_T_DEFINED
typedef struct _zmailer_client_t zmailer_client_t;
#define ZMAILER_CLIENT_T_DEFINED


//  Public API classes
#include "zmailer_msg.h"
#include "zmailer_server.h"
#include "zmailer_client.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
