/*  =========================================================================
    zmailer_client - zmailer server

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef ZMAILER_CLIENT_H_INCLUDED
#define ZMAILER_CLIENT_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/zmailer_client.xml" to make changes.
//  @interface
//  Create a new zmailer_client.
ZMAILER_EXPORT zmailer_client_t *
    zmailer_client_new ();

//  Destroy the zmailer_client.
ZMAILER_EXPORT void
    zmailer_client_destroy (zmailer_client_t **self_p);

//  Connect to server.
ZMAILER_EXPORT void
    zmailer_client_constructor (zmailer_client_t *self);

//  Print properties of the zmailer_client object.
ZMAILER_EXPORT void
    zmailer_client_print (zmailer_client_t *self);

//  Self test of this class.
ZMAILER_EXPORT void
    zmailer_client_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
