The following ABNF grammar defines the zmailer msg protocol:

    zmailer_msg     = *( MAIL )

    ;  Send a message by Mail (using predefined other parameters)            

    MAIL            = signature %d1 version from to subject request
    signature       = %xAA %xA0             ; two octets
    version         = number-2              ; Version
    from            = string                ; From field
    to              = longstr               ; To field
    subject         = longstr               ; Subject of the mail
    request         = longstr               ; Content text of the mail

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
